# Site settings

title: "Printrello"

description: "A web app that turns Trello Boards into dashboards you can print"
keywords: "trello, dashboards, print"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://printrello.github.io"
author: "John Peart"

asset-path: "/assets"
image-path: "/img"
css-path: "/css"
js-path: "/js"

logo-png: "/site/logo.png"
logo-svg: "/site/logo.svg"
logo-header-svg: "/site/logo-header.svg"
logo-header-png: "/site/logo-header.png"
logo-four-oh-four: "/app/404.svg"
social-media: "/site/social-media.png"
touch: "/site/touch.png"
pinned: "/site/pinned.svg"
pinned-colour: "#0079BF"

# Social settings
facebook-id: "1053585037989505" # For Facebook OpenGraph integration
facebook-slug: "john.robert.peart" # Automatically pre-pends http://facebook.com/
twitter-username: "johnpeart" # Twitter handle i.e. joebloggs
github-username:  "johnpeart"
github-repo: "https://github.com/printrello/printrello"
google-site-verification: "GMEFdAl3i-jN_Jkdb_jrS-LWZPUEQ7Bx4fPcyQ7YSCU" # GSV code; proves domain ownership

#Analytics
disable-analytics: true # Switch to "false" to start GA logging
google-analytics: "UA-27553664-1" # GA ID code

# Plugins and build settings

permalink: pretty
markdown: kramdown
future: false
sass:
    sass_dir: _sass
    sourcemap: true

plugins:
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from